/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}